### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by wywzxxz** [jacobwgillespie/heroku-minecraft#10]
when starting chlient,I get this error:

X:\[workspace]\[node.js]\minecraft\heroku-minecraft>coffee proxy/connect.coffee
 wywzxxz-heroku.herokuapp.com
Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.
TCP server listening on 0.0.0.0:25565
Attempting to open WebSockets connection to ws://wywzxxz-heroku.herokuapp.com/tu
nnel
Buffering TCP Data: localhosts
Buffering TCP Data: xxxx

WebSocket connected
Flushing buffered data over WebSockets: localhosts
Flushing buffered data over WebSockets: xxxx

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
  at errnoException (net.js:904:11)
  at TCP.onread (net.js:558:19)

I then read heroku log, seems it works fine on sever.
Any idea of this?

**Comment by jacobwgillespie** [comment]
There's a new version that cleaned up a lot of different issues - I'm going to close this for now, though let me know if you run into this issue again.
